### PR TITLE
Eclipse: Added Trunk Support For CorsixTH Eclipse Configurations

### PR DESCRIPTION
**Pull request by J-Shep**
#342 
Luna Workspace Configuration Screenshot
***In screenshot: the detected problems are not listed in the problems view because I've set it to only list problems for selected files/folders. This setting can't be included in the uploaded project configuration but instructions for using it are included in the setup readme file.***

I've created an Eclipse directory in the root CorsixTH directory which contains a folder for an Eclipse Luna workspace configuration containing a CorsixTH project.

The workspace and project have paths relative to the CorsixTH root directory, so they are ready to be used.

I've included a workspace configuration despite there only being one project because the benefit of giving this project its own CorisxTH workspace is that you can leave the files your working on open in the text editor view and then switch to another workspace to work with its projects files. Then you can just switch back to have all your CorsixTH files ready for you to continue using in the text editor view.

When this project is first opened a setup readme file will be displayed in the text editor view, telling users that they will need to install the Lua Development Tools plugin and a C++ development tools plugin.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Ok, so the language files should be added back.  There isn't really sufficient instructions in the README or any links on how to use this project or what it's for.  It isn't suitable for building CorsixTH without a lot of steps.

**Comment by J-Shep** [comment]
>> Ok, so the language files should be added back.

@TheCycoONE I've now done this.

>> There isn't really sufficient instructions in the README or any links on how to use this project or what it's for.

@TheCycoONE I've now replaced the README's setup instructions with a link to the WIP wiki "Eclipse Project Setup" tutorial, I will change the anchor link. I will add the other information you've asked for to the README & wiki tutorial.

>> It isn't suitable for building CorsixTH without a lot of steps.

@TheCycoONE When I want to compile CorsixTH in Windows with Visual Studio Express I simply have to open its .sln and then tell it to build the "CorsixTH" solution. I could make a compile script for Linux which could be executed by clicking a button in Eclipse.

**Comment by J-Shep** [comment]
>> @TheCycoONE When I want to compile CorsixTH in Windows with Visual Studio Express 2013 I simply have to open its .sln and then tell it to build the "CorsixTH" solution. In the tutorial I've made only Step 9 needs to be done every time CorsixTH is compiled since the settings configured in the other steps are remembered.

I will find out how to setup Eclipse to compile CorsixTH's C++ source code in Windows.

**Comment by Lego3** [comment]
Keep up the good work. :-) We could add C++ support in the future. This is a good first step.

**Pull request merged**
