### PR TITLE
[WIP] Drug casebook price impact [2]

### PR DESCRIPTION
**Pull request by benckx**
Issue: So far prices have no impact whatsoever. So player can increase all prices up to 200% without any consequence. It provides an unbalanced and undeserved advantage (it's almost a cheat).

The idea behind this patch is to compute the gap between the expected price level (given staff skill, fatigue, treatment reputation, cure effectiveness, etc.) and the price level in the casebook. Patient happiness is adjusted proportionally. Hospital reputation can only be impacted if the price distortion reaches thresholds (e.g. a 30% gap) and randomly (1 out of 10); this way it's not too impacting.

One patch had already been discussed earlier. This change is partially based on this conversation: https://github.com/CorsixTH/CorsixTH/pull/266

It's quite difficult to know exactly how to adjust all the variables (weight/influence of each variable, randomness, reputation changes, etc.) After testing with a few different settings, when I finally got something nice and more or less balanced, I run the following simulations. Let me know if you find a nice setting. I would be interesting to test it with poorly skilled staff.

Initial:
- Reputation: 582
- Balance: +44,000
- Cured: 131
- Highly skilled staff
- Wage requests granted

If I let it run for one year without any manual intervention and with different price levels.

All prices at 50%:
- Reputation: 704
- Balance: -26,000
- Cured: 233
- Price distortion: -0.70 to -0.50

All prices at 100%:
- Reputation: 652
- Balance: +44,000
- Cured: 225
- Price distortion: -0.45 to -0.25

All prices at 200%:
- Reputation: 617
- Balance: +171,000
- Cured: 231
- Price distortion: 0.25 to 0.45

I didn't look how it works exactly but it seems like reputation does not influence the number of patients coming to the hospital. That could be for another patch.

<b>Testing saved games:</b>
https://www.dropbox.com/sh/zfb57sosk92nbc9/AABcO6Q2Q70WDp1BORASEB9Sa/prices_impact?dl=0

### CODE REVIEW

**Comment by sadger** [comment]
Hi @benckx. We would love to get this included. Only thing that really needs doing is sorting out the commit history to one or maybe 2 commits.

**Comment by benckx** [comment]
Hi @sadger! Thanks for reaching out. Indeed I've been quite busy with my real developer job for the past few months. However I'd really love to finish this properly and see it included in the project.

I'll try to have a look at it within the coming weeks.

**Comment by sadger** [comment]
Oh welcome back @benckx, good to have you back! I have already done some partial rebasing and modifications to the code but haven't had time to finish it myself. We should probably discuss the best plan to go forward with this.

**Comment by benckx** [comment]
I've been discussing with @sadger for the past few weeks about the best way to finish this properly.

He proposed that I create a new branch from [his branch](https://github.com/sadger/CorsixTH/tree/price_impact_changes) so I can work from there, open a new PR and close this one.

Beside some minor edits, we agreed that the code doesn't need much work. But we still have to test and find the best value for each new parameter in order to find a good balance. Here is a summary of these parameters, with their current values:

#### Thresholds
* Under-pricing threshold: `-0.3`
* Over-pricing threshold: `0.3`
* Fair and well adjusted pricing: `[-0.15, 0.15]`

#### Frequencies
Every time a patient has to pay and feels like the price is distorted, we must decide how often the patient leaves without paying, how often this changes the reputation and how often the adviser warns the player.

* Frequency of patient leaving without paying when over-priced: `1/5`
* Frequency of adviser warning (distortion): `1/10`
* Frequency of adviser warning (fair prices): `1/20`
* Frequency of reputation change: `1/5`

#### Weights
##### Expected price level
* Staff service quality weight: `0.40`
* Reputation weight: `0.35`
* Effectiveness weight: `0.10`
* Randomness weight: `0.15`

(I consider dropping the latter as there's already some randomness introduced with the frequencies.)

##### Staff service quality
* Skill weight: `0.7`
* Fatigue weight: `0.2`
* Happiness weight: `0.1`

##### Reputation changes
* Under-priced: `+1`
* Over-priced: `-2`

Regarding reputation influence on the spawn rate, I made it linear so there isn't really any declared parameter to adjust, although the effect should maybe get weighted as well.

So there're about 15 parameters to adjust, knowing that the thresholds and the frequencies are more impacting than the weights.

I'll run a few simulations later and provide the results here.

**Comment by sadger** [comment]
Lets go ahead with the new branch, let make all future discussion on the new PR. Please can you refer to this PR in your new PR as it has useful discussions which we can still read after we close it.

**Comment by TheCycoONE** [comment]
I'll close this when the new PR is ready.

**Comment by sadger** [comment]
Closed due to new one opened #971

**Pull request closed without merging**
