### PR TITLE
More natural meandering #1376

### PR DESCRIPTION
**Pull request by Brainsample**
Here's an attempt to create a PR ... let's hope it works. :)

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Avoid multiple unrelated issues in the same PR.

Your problem is that you are doing all your work on master, which sooner or later is going to backfire.

Read our contributing.md and maybe a git tutorial.

**Comment by Brainsample** [comment]
Of course I made a mess, and I couldn't find a way to correct it.
These things happen when you use software for the first time, right? :)
Can you ignore the unrelated patch, or should I start from scratch?

**Comment by TheCycoONE** [comment]
Close this pr

```
git branch mess
git reset --hard origin/master
git checkout -b meander
git reset --hard eb2b04
```
Open a new PR from meander

Your other patch will be in mess and can be rebased or cherry picked later.

**Comment by Brainsample** [comment]
Great help, thank you very much. :)

**Pull request closed without merging**
