### PR TITLE
[RDY] Bump vcpkg deps and add luasec

### PR DESCRIPTION
**Pull request by TheCycoONE**
brotli                                 1.0.9#1
bzip2                                  1.0.8#1
catch2                                 2.13.1#1
ffmpeg                                 4.3.2#12
freetype                               2.10.4
libflac                                1.3.3#5
libmodplug                             0.8.9.0#7
libogg                                 1.3.4#3
libpng                                 1.6.37#14
libvorbis                              1.3.7#1
lpeg                                   1.0.2-1
lua                                    5.4.3#1
luafilesystem                          1.8.0-1
luasec                                 1.0.1
luasocket                              2020-09-14
mpg123                                 1.26.5
openssl                                1.1.1k#1
sdl2-mixer                             2.0.4#11
sdl2                                   2.0.14#4
zlib                                   1.2.11#10

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Old to new:
https://github.com/CorsixTH/vcpkg/compare/10ca4c5ba5218c14c4bf91570afe8bd5d63da3...CorsixTH:c2691026a5e5aad05d7e7d89d605ccb595cbbcb6

new corsixth tip to microsoft's vcpkg master (as of this comment):
https://github.com/microsoft/vcpkg/compare/e6dcc079c81161786eb7b052209a2047e79f2c6c...CorsixTH:c2691026a5e5aad05d7e7d89d605ccb595cbbcb6

**Review by lewri — APPROVED** [review]
Looks okay -- but ideally you'll want someone who knows CMake to review

**Comment by lewri** [comment]
Launches fine via Appveyor build and playable and savable. Can't say about load though until #1879 is looked at

**Comment by lewri** [comment]
After injecting toby's fix this appeared to have built and plays fine in appveyor's version

**Comment by TheCycoONE** [comment]
Ok, I think Microsoft is going to want some changes before they let me upstream luasec but this is good for this release.

**Pull request merged**
