### PR TITLE
[RDY] Add configurable option for room information dialogs

### LINKED ISSUE #337: debug mode changes game behaviour (hides first built room information)
This behaviour was intentional, it was introduced in 41c8b342b9ba162d1b2c4f1552cb4588ffd8279d but my feeling is that it's an unexpected / seemingly unrelated functionality change from the act of debugging, and in the case of #256 actually made debugging harder because toggling information off prevented the error.

@MarkL1961 mentioned that this had been discussed in google issues.  I haven't been able to find the issue in a quick skim, but if someone can find it there it would be interesting to see the reasons why this change was introduced in the first place.

My recommendation at this point is to introduce a config option specifically for whether to show first time room information dialogs, and to disassociate it with the debug flag.

### PR DESCRIPTION
**Pull request by tobylane**
Fixes #337

### CODE REVIEW

**Comment by tobylane** [comment]
I messed up my testing. This is already fixed.

**Comment by Alberth289346** [comment]
Hmm, and I liked your positive name "room_information_dialogs" instead of the negated form "room_information_dialogs_off" which just complicates matters without good reason ;)

**Comment by TheCycoONE** [comment]
@tobylane why did you think this was already resolved. It still depends on `debug`. Can we reopen this?

**Comment by tobylane** [comment]
Fixed and ready.

**Pull request merged**
