### PR TITLE
Bump vcpkg commit tag

### PR DESCRIPTION
**Pull request by TheCycoONE**
The biggest change is the bump from SDL2_mixer 2.0.4 to 2.6.1 flac, ogg vorbis, and mp3 support are now all built in without extra libraries.

Other significant package changes:
catch2 used for unit tests is now 3.x rather than 2.x
sdl2 bumped from 2.0.20 to 2.24.1

There is now a fluidsynth option for sdl2_mixer in vcpkg, but this commit does not enable it.

Fixes building with vcpkg since zlib is no longer available at the old URL.

before:
```
  * brotli[core]:x64-windows -> 1.0.9#2
  * bzip2[core]:x64-windows -> 1.0.8#2
    catch2[core]:x64-windows -> 2.13.9
    ffmpeg[avcodec,avformat,core,swresample,swscale]:x64-windows -> 4.4.1#12
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.11.1#1
  * libflac[core]:x64-windows -> 1.3.4
  * libmodplug[core]:x64-windows -> 0.8.9.0#9
  * libogg[core]:x64-windows -> 1.3.5
  * libpng[core]:x64-windows -> 1.6.37#17
  * libvorbis[core]:x64-windows -> 1.3.7#2
    lpeg[core]:x64-windows -> 1.0.2#2
    lua[core,tools]:x64-windows -> 5.4.4#1
    luafilesystem[core]:x64-windows -> 1.8.0#2
    luasec[core]:x64-windows -> 1.1.0
    luasocket[core]:x64-windows -> 3.0.0
  * mpg123[core]:x64-windows -> 1.29.2#3
  * openssl[core]:x64-windows -> 3.0.3
  * pkgconf[core]:x64-windows -> 1.8.0#2
    sdl2[core]:x64-windows -> 2.0.20#3
    sdl2-mixer[core,dynamic-load,libflac,libmodplug,libvorbis,mpg123,nativemidi]:x64-windows -> 2.0.4#16
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-02-10
  * vcpkg-tool-meson[core]:x64-windows -> 0.60.2#2
  * yasm-tool-helper[core]:x64-windows -> 2020-03-11#1
  * zlib[core]:x64-windows -> 1.2.12
```

after:
```
  * brotli[core]:x64-windows -> 1.0.9#3
  * bzip2[core,tool]:x64-windows -> 1.0.8#3
    catch2[core]:x64-windows -> 3.1.0#1
    ffmpeg[avcodec,avformat,core,swresample,swscale]:x64-windows -> 4.4.1#20
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.12.1#2
  * libmodplug[core]:x64-windows -> 0.8.9.0#10
  * libpng[core]:x64-windows -> 1.6.37#19
    lpeg[core]:x64-windows -> 1.0.2#2
    lua[core,tools]:x64-windows -> 5.4.4#2
    luafilesystem[core]:x64-windows -> 1.8.0#2
    luasec[core]:x64-windows -> 1.1.0
    luasocket[core]:x64-windows -> 3.0.0#1
  * openssl[core]:x64-windows -> 3.0.5#5
  * pkgconf[core]:x64-windows -> 1.8.0#3
    sdl2[core]:x64-windows -> 2.24.1
    sdl2-mixer[core,libmodplug,nativemidi]:x64-windows -> 2.6.1#2
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2022-09-04
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-02-10#1
  * vcpkg-tool-meson[core]:x64-windows -> 0.63
  * zlib[core]:x64-windows -> 1.2.12#2
  ```

### CODE REVIEW

**Comment by TheCycoONE** [comment]
I suspect the catch2 bump broke unit tests in windows. I'll want to address that before this is merged.

**Comment by lewri** [comment]
Is the zlib bump temporary until this is patched?
https://github.com/microsoft/vcpkg/pull/27226

**Comment by lewri** [comment]
Also is there anything worthy of note here to be remembered for our next release notes for packagers?

**Comment by TheCycoONE** [comment]
> Is the zlib bump temporary until this is patched? [microsoft/vcpkg#27226](https://github.com/microsoft/vcpkg/pull/27226)

Probably, we'll have to do this again. And I need to make a decision on either disabling unit tests for now or upgrading everywhere to catch3 for now.

**Comment by Alberth289346** [comment]
I don't know what removing `-DBUILD_TESTING=OFF` does exactly, but it seems to stop skipping things so that is likely fine.
Otherwise, LGTM.

**Review by lewri — APPROVED** [review]
Merge when you're ready -- let me know when I can start rebasing our affected PRs

**Pull request merged**
