### PR TITLE
new function added: spacebar to center view

### PR DESCRIPTION
**Pull request by xuancong84**
new function: when there are announcements for missing staff or handyman in any room, the player can press space to center view on that room, so that he can find the room immediately, instead of search for the room

### CODE REVIEW

**Comment by TheCycoONE** [comment]
I strongly recommend you don't work out of your master branch.  There is a lot of history in this pull request that doesn't belong with it.

Start by closing this pull request, then:
git checkout -b currentwork
git checkout master
git reset --hard origin/master

At that point it's a matter of straightening out your current work.  Maybe jump on #corsix-th or read some git guides.

**Comment by xuancong84** [comment]
Sorry, I got messed up in the beginning. Actually, I reverted back some of
my earlier commits. So there are in total 2 modifications:
1. dynamic information display during pause
2. spacebar to center view

Since I am using eclipse egit, I am not sure how to "checkout -b" and
revert back properly.

If there are no conflicts, please accept this pull request. Next time I
will do it correctly. Thanks!

xc

On Fri, Jan 30, 2015 at 10:28 PM, Stephen E. Baker <notifications@github.com

**Comment by wolfy1339** [comment]
If you are using Windows, I highly recomment to download <a href="https://github.com/msysgit/msysgit/releases">MSYSGit</a>.
Instal it, then open Git Bash (Termainl containing Git), then you may enter the commands TheCycoOne gave you.
And also read some more about Git at http://git-scm.com/doc

**Comment by TheCycoONE** [comment]
@xuancong84 you run these commands in the terminal.  The instructions in CONTRIBUTING.txt are detailed step by step.

Once you have clean pull requests we can go over any changes needed.

**Comment by xuancong84** [comment]
Thanks! But I am using Linux/Ubuntu Eclipse egit.
I have figured out how it works. I will re-commit everything.

xc

**Comment by xuancong84** [comment]
Thanks! I have figured out how it works. I will re-commit the two changes
and issue a single pull request.

Cheers,
xc

**Pull request closed without merging**
