### PR TITLE
change symbols in zh_CN level introduction text to workaround game hang

### LINKED ISSUE #1449: Simplified Chinese hangs the game
#### Describe the issue

I set the game to use Simplified Chinese langauge to play (with either original game downloaded from GOG or the game with Chinese patch applied (which is said to be extracted from an official Simplfied Chinese version) ).

When I start game with default options (First game off and difficulty as "Doctor"), the game hangs after the Ludo-like screen, and doesn't enter the main game screen. (The BGM is changed however.)

Sometimes the screen is changed, but the mouse cursor cannot move, and thus cannot play.

Enable first game seems to be able to workaround this, but I didn't try whether it will hang after.

Traditional Chinese is okay.

#### Steps to Reproduce
1. Set a TTF font

2. Change language to Simplified Chinese ("简体中文")

3. Start game with default options.

#### System Information
**CorsixTH Version:** 0.62

**Operating System:** Linux (AOSC OS)

**Theme Hospital Version:** GOG

#### Gamelog.txt
Nothing is in it.

### PR DESCRIPTION
**Pull request by Icenowy**
The text layout code in the game expects a long string to have spaces,
new lines or line breaks to break the line to suite the display size.
However, Chinese texts usually doesn't satisfy this, so they may hang
the code.

Change full-width Chinese symbols in level introduction texts to western
half-width ones add a space, to workaround this problem.

Signed-off-by: Icenowy Zheng <icenowy@aosc.io>

--

This fixes #1449 .

### CODE REVIEW

**Comment by TheCycoONE** [comment]
@Icenowy would it be better if we allowed the algorithm to break after each of those characters instead? Do you have a list?

**Comment by Icenowy** [comment]
@TheCycoONE 
```
"，", "。", "？", "！", "－", "；"
```
are in the game translation now.

**Comment by Icenowy** [comment]
\uff0c, \u3002, \uff1f, \uff01, \uff0d, \uff1b

as Unicode codepoints

**Comment by TheCycoONE** [comment]
Closing in favour of #1478

**Pull request closed without merging**
