### PR TITLE
Update screenshot URLs in metainfo

### PR DESCRIPTION
**Pull request by rmnvgr**
**Describe what the proposed change does**
- Update screenshot URLs in metainfo to the new images

**Do not merge until corsixth.com points to the new website**

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Question - when corsixth.com moves there will be a disruption - does the github url always work? Perhaps we should switch to that domain now to avoid any disruption?

**Comment by rmnvgr** [comment]
The GitHub URLs will always work indeed. Note that Flathub downloads a copy of the images to serve them itself, so it won't disrupt anything there. Not sure about other package front-ends though.

I can of course change to GitHub URLs.

**Comment by TheCycoONE** [comment]
Site has been moved, we probably want this now

**Comment by rmnvgr** [comment]
Nice! I checked that the URLs were correctly loading, this is ready to be merged.

**Pull request merged**
