### PR TITLE
[RDY] Add English names of languages beside the native name in options

### PR DESCRIPTION
**Pull request by tobylane**
The change in strings.lua affects https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/app.lua#L721 and https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/app.lua#L779 but I'm not sure what to do.

The longer text spills well outside the box, but it looked bad simply widening the background element. How do you want it to look?

### CODE REVIEW

**Comment by MarkL1961** [comment]
What about doing this as an hover text as those only show when you hover and can expand easily ?

**Comment by tobylane** [comment]
```lua
langs[#langs + 1] = {text = lang, font = font, tooltip = _S.tooltip.options_window.language_dropdown_item:format(lang, eng_name)}
```

That would look like this. I don't get that tooltip, not even with a new config.txt or without my changes.

**Comment by MarkL1961** [comment]
Does the tool tip work on hover the button or the name label?  It only needs to work from one of them and you could use the other

**Comment by MarkL1961** [comment]
I have just looked at the game to see what you are doing and I can see the problem with my suggestion.
Only the selected language as a hover text.
You could widen the menu and then widen the text area of the dropdown to show the extended text

**Comment by TheCycoONE** [comment]
Linking to the relevant issue and discussion: #84

**Comment by MarkL1961** [comment]
From the original issue it is clear some can't see the benefit of this, but let's suppose your pc lacks the correct font and all you see is squares or you accidently select the wrong language it is useful to see the language selected and then perhaps the English name to correct your mistake..

Yes you can correct it in config, but how may times have we had someone not know where to find it?

Tooltips is deactivated, can that be reversed so the option stated above becomes a solution?
Can we widen the drop down to show more text?  (also suggested above)
What about undo so that you can go back to the way things were?
Does someone have another idea?

**Comment by tobylane** [comment]
This enables tooltips with sensible defaults, which are also used for the difficulty setting of a new campaign.

**Comment by TheCycoONE** [comment]
Code looks good to me @tobylane - is this RDY?

**Comment by tobylane** [comment]
It is, sorry for the delay.

**Comment by TheCycoONE** [comment]
No worries, holding for after the release. Make sure I remember right after :smile:

**Pull request merged**
