### PR TITLE
Lua 5.2 and 5.3 compatibility

### PR DESCRIPTION
**Pull request by TheCycoONE**
With this pull request the game is playable in Lua 5.2, and is able to load all of my save games.  Save games should be fully compatible back and forth between Lua 5.1 and Lua 5.2.

The risk of impacting Lua 5.1 is pretty small.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
1. Command line arguments are actually functioning, I was simply lacking luasocket in that build folder.
2. I believe that th_getfenv is actually functioning.  I printed the keys to the tables returned in lua 5.2 and lua 5.1 and they are identical.  That suggests the problem is somewhere else in persistence.

**Comment by TheCycoONE** [comment]
I managed to get some help from #lua on freenode.  At least in the case of music it's because we're trying to set the metatable to the environindex, which in lua 5.2 we mapped to the first upvalue, but functions created with lua_setfuncs(state, reg, 0) have no upvalues.

**Comment by TheCycoONE** [comment]
Re-based on the latest master, and added casts to avoid undoing the work done by @Alberth289346

**Comment by TheCycoONE** [comment]
Travis failure was due to sourceforge downloads again.  Will close and open to trigger rebuild.

**Comment by alanwoolley** [comment]
@TheCycoONE You don't need to close/open. If you navigate to the failing build on Travis CI, then you should find a 'restart build' button on the right. It'll pull the commit in again and retry the build. You might need to login with your GitHub account, I'm not sure.

**Comment by TheCycoONE** [comment]
@alanwoolley Noted, sorry for the noise.

**Comment by Alberth289346** [comment]
Ran a small test by building a GP office, and noticed the tile cursor jumping around in a weird way. See the attached image. The needle cursor move parallel to the wall of the GP office.

jumping tile cursor

**Comment by TheCycoONE** [comment]
Last commit fixes the issue @Alberth289346 mentioned above.  When we are ready to merge it should be rebased into b42445b

**Comment by Alberth289346** [comment]
Found another issue, if you change zoom with the mouse wheel, the world moves a tile toward the bottom right. It does not matter where the cursor is in the screen, or whether you zoom in or out.

For best effect, turn the wheel slowly so the program can keep up and sees it as a sequence of small changes.

**Comment by TheCycoONE** [comment]
Removes a few more useless math.floor statements and fixes the zoom issue @Alberth289346 found.  I had really gone overboard with the math.floor for lua 5.3 compatibility.

The next two commits fix a conversion warning introduced in the new debugging functions.

**Comment by Alberth289346** [comment]
Crash when clicking the 'research' button:
./CorsixTH/Lua/dialogs/fullscreen/research_policy.lua:113: attempt to call field 'gfind' (a nil value)

Doesn't exist any more in lua 5.2 see http://lua-users.org/lists/lua-l/2013-04/msg00117.html
Seems it's called 'gmatch' now (also in that link). 'ack' says there is only 1 gfind in the program.

**Comment by TheCycoONE** [comment]
Fixed research_policy, replacing gfind with gmatch.  Thanks @Alberth289346

**Comment by Alberth289346** [comment]
Line 405 of CorsixTH/Src/th_lua.cpp, below the line
printf("boolean %s\n", lua_toboolean(L, i) ? "true" : "false");

has a TAB character in the line.
Otherwise, it looks fine to me (looked a the combined diff from the master branching point)

**Comment by TheCycoONE** [comment]
Fixed whitespace error pointed out by @Alberth289346 and rebased on lasted master, squashing all fix commits.

**Pull request merged**
