### PR TITLE
Add new language (Ukrainian)

### PR DESCRIPTION
**Pull request by JurecStrongman**
*Fixes #*

**Describe what the proposed change does**
- Adds ukrainian language
- Almost all strings translated
- Maybe need some more work but mostly playable

### CODE REVIEW

**Comment by lewri** [comment]
Sorry about keeping having to approve the runs

**Comment by lewri** [comment]
@JurecStrongman if there's strings you need help with understanding feel free to reach out on Discord or Matrix. Otherwise let me know if finished =]

**Comment by JurecStrongman** [comment]
> @JurecStrongman if there's strings you need help with understanding feel free to reach out on Discord or Matrix. Otherwise let me know if finished =]



> @JurecStrongman if there's strings you need help with understanding feel free to reach out on Discord or Matrix. Otherwise let me know if finished =]
How can i get strings which is not translated? Found one by myself but wondering is there more

**Comment by JurecStrongman** [comment]
@lewri i think translation is done

**Pull request merged**
