### PR TITLE
[RDY] Add github issue template

### PR DESCRIPTION
**Pull request by TheCycoONE**
GitHub recently introduced support for issue templates: https://github.com/blog/2111-issue-and-pull-request-templates

Try it out at: https://github.com/TheCycoONE/issue-template-test/issues/new

### CODE REVIEW

**Comment by Alberth289346** [comment]
looking good, maybe link to a wiki page where to find the gamelog ?
perhaps "try to find a savegame just before the issue happens?"
maybe add that to "steps to reproduce"

**Comment by TheCycoONE** [comment]
Alright I've tried to use @Alberth289346's suggestions. Any other comments?

**Comment by Alberth289346** [comment]
:+1:

**Comment by TheCycoONE** [comment]
Pinging @Lego3

**Comment by Lego3** [comment]
Ah, sorry. I follow updates in the ForkHub app for Android, and there the template doesn't work... so I forgot about it.

The only thing would be whether this same pull request should move the other file into the .github folder as well? (CONTRIBUTING) Or do we want README and CONTRIBUTING to stay in the root?

**Comment by TheCycoONE** [comment]
@Lego3 My feeling is that ISSUE_TRACKER.md is a clear case of a file that has no meaning outside of GitHub so it definitely belongs in .github, README.md is probably in that category too so if it works under .github I'll move it there.

CONTRIBUTING.txt isn't as clear cut, I think it has just as much value read locally as it does in GitHub, so I'd prefer to leave it where it is.

Sensible?

**Comment by Lego3** [comment]
Yep.

**Comment by TheCycoONE** [comment]
I did a test in my repo with a readme.txt at the root and readme.md in .github and github ended up using the readme.txt, so I think this has to stay as is. Marking [RDY].

**Pull request merged**
