### PR TITLE
Removing old MacOSX meta-information SDLMain file.

### PR DESCRIPTION
**Pull request by Alberth289346**

### CODE REVIEW

**Comment by Alberth289346** [comment]
CorsixTH/SDLMain also exist I found, the SDLMain.h and SDLMain.m in there are also 5 years old, the CmakeLists.txt seems newer for some lines (it mentions SDL2).
I guess someone with a Mac should have a look at this

**Comment by TheCycoONE** [comment]
@admdly could you have a look at this remaining SDLMain situation and whether it can safely be removed?

**Comment by admdly** [comment]
I'll have a look at this later this evening. I had previously planned to arrange removal myself but hadn't gotten around to it.

**Comment by TheCycoONE** [comment]
@admdly did you make any progress on this?

**Comment by admdly** [comment]
Apologies for the delay, I have been extremely busy and will be for a little while longer. My understanding is the file can be removed, but I have not checked that it builds correctly without the file as of yet. Due to the large amount of changes to dependencies I am not even sure if the build completes at all at this point for the Mac.

I hope to look into this as soon as possible to see what, if anything, is broken and if the file can be safely removed. I will report back once tested.

**Comment by admdly** [comment]
I've quickly checked this and this file **can** be safely removed. There is a host of other CMake issues and an issue preventing a build, but these are not related in any way to SDL.

I'll keep looking into these as time allows and create PRs to correct these issues where appropriate.

**Comment by TheCycoONE** [comment]
Thanks @admdly, I'll hold off merging this until you get your builds working and can do actual tests. Feel free to discuss your issues with the build on irc or the mailing list.

**Comment by TheCycoONE** [comment]
Also verified by tobylane.

**Pull request merged**
