### PR TITLE
[RDY]1334: Adds a no action check

### PR DESCRIPTION
**Pull request by pschoffer**
Fix for #1334

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Just add some noise so it shows up in the game log along with information to identify the patient (type, x, y etc.)

Be clear in code that an invariant has been violated.

Longer term, we need to cut down on action queue meddling and enforce that invariant

**Comment by pschoffer** [comment]
OK that sounds good. I will unify the `getCurrentAction` logic somewhere with logging. To be continued:)

**Comment by pschoffer** [comment]
@Alberth289346 thanks for the comment. I see your point (from both of you:)). and as I mentioned I will prepare the contra solution as suggested.

**Comment by TheCycoONE** [comment]
@pschoffer how does this error look in the output?

**Comment by pschoffer** [comment]
I get this when not catching in in test. So that looks good I think.
screenshot from 2018-01-24 11-33-59

**Comment by TheCycoONE** [comment]
Looks great to me, thanks

**Comment by TheCycoONE** [comment]
We should improve error to dump a call stack, but that can be another issue.

**Pull request merged**
