### PR TITLE
[RDY] Fix edit room hotkeys

### PR DESCRIPTION
**Pull request by TheCycoONE**
self:registerKeyHandlers was calling the function on the
subclass. Explicitly register on the current class.

Fixes the major issues in #1529 
I haven't yet tested the old save.

### CODE REVIEW

**Comment by mugmuggy** [comment]
That works ok.

The old save has an afterLoad with a call to self:registerKeyHandlers also, but that doesn't get called at all. It also leads to the room requiring to be completed then edited again for the hotkeys to become active.

This occurs on new games, started on 0.63 beta1 as well, if the hotkey is changed and the save reloaded, and the UI is open it is disfunctional until the UI is reopened again.

The saves issue is more a nice to have, as there is a simple workaround, complete room then edit, or cancel room and start over.

**Comment by TheCycoONE** [comment]
I had changed the afterLoad as well, but was tired at the time and neglected to include it in the commit. I'll fix UIPlaceObject's afterLoad not being called as well.

**Comment by TheCycoONE** [comment]
I've fixed loading saves made with the current version with new hotkeys.

**Comment by TheCycoONE** [comment]
Fixed loading old saves that had dialogs open. I think this now fixes everything from #1529

**Comment by TheCycoONE** [comment]
@mugmuggy could you check and merge this if ok?

**Comment by mugmuggy** [comment]
All good on trunk saves and happy to leave the previous saves with the editing of room.

**Pull request merged**
