### PR TITLE
Re-Organise french.lua, Translation fixes & formatting/organisation fixes

### PR DESCRIPTION
**Pull request by wolfy1339**
This PR re-organises french.lua to match the layout of english.lua

### CODE REVIEW

**Comment by bobcanthelpyou** [comment]
Is it useful to order the translation files similar as the english.lua file?

Other translation files don't have an original language file in the background.

Is the order of the output of the debug-strings-new-grouped.txt file (created by 'dump strings') always the same? And could that file be a better reference for reorganize the language files in a better way?

**Comment by wolfy1339** [comment]
There were some other fixes too mixed in there.

> Is the order of the output of the debug-strings-new-grouped.txt file (created by 'dump strings') always the same?

I'm not sure about that, but I think so.
> And could that file be a better reference for reorganize the language files in a better way?

Well, I would agree with you. the language files should be prganized the same

**Comment by TheCycoONE** [comment]
@wolfy1339 is it possible for you to separate the fixes from the reordering. It's pretty hard to review the fixes when everything is moved.

**Comment by wolfy1339** [comment]
I can try

**Comment by wolfy1339** [comment]
I just pushed the fixes and will push the reordering later

**Comment by TheCycoONE** [comment]
Thanks @wolfy1339

**Comment by wolfy1339** [comment]
@TheCycoONE All done

**Comment by TheCycoONE** [comment]
@bobcanthelpyou there is no 'order' for a lua table, unless you index it 1, 2, 3..., as such the dump doesn't have an order and it's not something that could easily be fixed.

**Pull request merged**
