### PR TITLE
Draw floor shadows immediately after floor tiles

### LINKED ISSUE #1929: [Bug] Artifacts visible in shadows when zooming with direct_zoom
#### Describe the issue

With the direct_zoom feature enabled, there are pixels between tiles which are slightly darker than the rest of the shadow. 

#### Steps to Reproduce
1. Set `direct_zoom = true` in CorsixTH `config.txt`.

2. Start a new game.

3. Zoom in or out closely watching the shadows near northwest walls.

4. At certain zoom levels single pixels along seems between tiles will appear darker, as the translucent shadow rendering is likely overlapping by a single pixel. See screenshot below:

#### Save Game

This should be easily reproducible from a new game.

#### Expected Behavior

There shouldn't be any visible doubly shaded pixels.

#### System Information
**CorsixTH Version:** *0.65*

**Operating System:** *Linux*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt

The Gamelog likely does not contain any useful information

### Additional Info

This is a picture of the issue:
shadow-artifacts

### PR DESCRIPTION
**Pull request by flackr**
*Fixes #1929*

**Describe what the proposed change does**

This change draws each floor shadow immediately after the floor tile.

By drawing the floor shadows immediately after drawing the floor tile we ensure that no pixel is shaded by shadow twice, as if it would be it would first be covered by the adjacent floor tile if there will be overlap.

### CODE REVIEW

**Comment by mugmuggy** [comment]
I've got this same change in a playground code base, where I was looking at some of the rendering issues, but never took a look at shadows under zoom, or if I did I ignored it. Also using the inbuilt FPS counter, I was getting an ever so slight degradation (under extremes, zoomed out with 100s of entities) degradation. Maybe your other zoom changes improve on that anyway.

**Comment by flackr** [comment]
@mugmuggy it's worth noting that the direct_zoom feature (which this change is intended to stabilize) is a significant performance improvement when zoomed out. On my system I see a 27% fps increase.

**Comment by flackr** [comment]
Here's a side-by-side of the fixed shadows with `direct_zoom = true` (left is master, right is with this fix)
direct-zoom-shadows

**Comment by flackr** [comment]
It occurs to me there's probably no need to separate the 1st pass at all if the floor shadows which should be below everything else were drawn as part of the second pass

**Comment by TheCycoONE** [comment]
Yes, the tiles were only drawn first because there use to be an optimization in the old backends that made it quicker to draw that way, since that's gone it's no longer useful.

**Comment by flackr** [comment]
Done, I've merged the two render passes and updated the comments.

**Pull request merged**
