### PR TITLE
Set direct zoom to true as default

### PR DESCRIPTION
**Pull request by lewri**
Attempting #2288 again

### CODE REVIEW

**Comment by TheCycoONE** [comment]
I believe you shouldn't need to do that, we wanted nil to represent the default so we could interpret it either way.

**Comment by TheCycoONE** [comment]
Ah I see... the problem with explicitly marking things... actually the problem with the way we do config, is that we can't differentiate between defaults and user preferences which makes it hard to evolve.

**Comment by lewri** [comment]
If you set a value to nil in `config.txt`, the game attempts to overwrite the nil value on every load. 
Ideally you don't want nil for such a setting here, as it now unnecessarily tries to replace it... with nil.

The setting imo should be a real representation of the status of direct zoom, rather than assuming nil to be true. 

The other debug lines as nil probably aren't the best either, they might be best using a format like player name as `[[]]`

**Comment by TheCycoONE** [comment]
The problem I was trying to solve for originally was that directZoom was going to be false for everyone until they opted in. When you install a new version of the game you keep your config so we would have needed to tell everyone to change it. We could have said in the update notes, but most people wouldn't notice.

Thoughts?

**Comment by Alberth289346** [comment]
#1992

**Comment by lewri** [comment]
> The problem I was trying to solve for originally was that directZoom was going to be false for everyone until they opted in. When you install a new version of the game you keep your config so we would have needed to tell everyone to change it. We could have said in the update notes, but most people wouldn't notice.
> 
> Thoughts?

It may not matter all in all. And as I've stepped away from this for over a month I've lost the moment of understanding.

Currently the direct_zoom config value gets interpreted as `nil == true` in 0.66. 
In 0.65 we had `nil == false`. In essence, we went from an opt-in model to an opt-out model. So unless the user specified a choice on that value they were given the default. But in all other boolean settings that impact a user generally have a literal `true` or `false`, which gives a definitive statement on what the value is.

If you implement this change post 0.66, you have no additional unexpected impact on user experience (ergo, <=0.65 to 0.67 will always end up enabling direct zoom if nil or not present). If the config value was `nil`, it will be automatically changed to `true` during `App:fixConfig()`-- thus representing our currently enforced default. If the user expressly set a `true` or `false` value, it is not changed at all.

As for #1992 there is a great point about experimental changes using `nil` from you Cyco and I respect it. However, direct zoom is now past this point and we should seek to correct its course now it is enabled by default (unless we're still planning to work it again). 
Perhaps because `nil` use for experimental stuff is not showing as reliably suitable, but that is a conversation to be had in that issue, not here (and the other issue of `nil` being changed to `nil`).

**Comment by lewri** [comment]
Closing for now

**Pull request closed without merging**
