### PR TITLE
V065 release notes

### PR DESCRIPTION
**Pull request by TheCycoONE**

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Is this the right way to do a release description in appdata; or are they looking for a shorter short log. Is the formatting correct, I saw the tag support is pretty limited.

**Comment by TheCycoONE** [comment]
In a brief search few major projects included releases at all, and even fewer provides descriptions, those that did tend to be short.

appstreamcli dump hedgewars.desktop (no releases)
appstreamcli dump wesnoth.desktop (no releases)
appstreamcli dump openttd.desktop (no releases)
appstreamcli dump openrct2.desktop (no releases)
appstreamcli dump org.kde.plasmashell (past 4 stable releases, no notes)
appstreamcli dump org.gnome.meld.desktop (past 4 releases, includes notes no more than 10 points per)

**Review by rmnvgr — APPROVED** [review]
Looks good to me, it validates.

Having the full release notes is fine, if you look at Inkscape or GIMP, for their important releases it can get quite lengthy.

**Review by tim77 — APPROVED** [review]
LGTM. `appstream-util` passed. And agree it's Okay to have long changelogs.

**Pull request merged**
