### PR TITLE
[RDY] Enum modernization

### PR DESCRIPTION
**Pull request by TheCycoONE**
I reviewed all enum usage in CorsixTH and converted to `enum class` and/or added type specifiers as appropriate for improved type safety, and ease of analysis.

### CODE REVIEW

**Comment by Alberth289346** [comment]
Conversion of alignment string to enum value seems to be duplicated, and enumeration class names are not consistent, but both are out of scope for this patch I think.

**Comment by TheCycoONE** [comment]
Yes, I noticed both issues too. I still don't really know what naming convention we want for classes, and haven't settled on one yet.

```
iso_names_their_classes_like_this
Stroustrop_names_his_classes_like_this
JavaStyleIsPopular
THPrefixesAreUsedBySomeVendorsLikeApple
```

**Comment by Alberth289346** [comment]
I always use CamelCase for classes. Prefixes are silly, use a namespace if you're worried the code will be used in another library with clashing names (ie not going to happen is my guess).

I use lower_case for variables. Functions/methods are always a bit of a problem, I often use CamelCase too, as they have an active form DoSomething, while classes usually have a more passive wording like DataStore. My alternative form for functions is like_variables. notInitialCamelCase for functions could work too, but I find it less pretty, not sure why.

I would likely write enum values AS_ALL_UPPERCASE, as they are constants to me, but that may look bad together with the forced prefix.

**Comment by TheCycoONE** [comment]
Strostrup and the C++ Core Guidelines have strong objections to ALL_CAPS being used for anything but preprocessor macros. I agree with their reasoning.

**Comment by Alberth289346** [comment]
Except for the standard #include protection, I don't use preprocessor macros in c++. In c, I only use it for plain expressions, that should be 'inline' functions, but c89 (yes, indeed, that old :( ) doesn't have that.

**Pull request merged**
