### PR TITLE
[RDY] Update Rsync filter file and use

### PR DESCRIPTION
**Pull request by tobylane**
This adds the newer folders to the rsync list and changes the OS X target of the rsync to the MacOS folder where the CorsixTH executable is. It's done this way in the 0.40 release and I'm unsure why others haven't seen this problem (it's hidden if you move the app to the top folder of the repository). Only the Icon.icns is left in Resources because that sets the Finder icon, which may not be in control of CMake, my testing didn't make that clear.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Is the RequiredResources.txt change related to this?

**Comment by tobylane** [comment]
That change just adds the newer folders, it will help any platform that uses the filter file. It's not necessary for the OS X app to work.

**Comment by TheCycoONE** [comment]
Alright, could you move it to a separate commit.
```
git reset HEAD^
git add  CorsixTH/CMakeLists.txt
git commit --amend
git add  CorsixTH/RequiredResources.txt
git commit
git push -f
```

**Comment by tobylane** [comment]
Done.

**Pull request merged**
