### PR TITLE
Update russian.lua

### PR DESCRIPTION
**Pull request by Matroftt**
**Describe what proposed changes do**
- Translates debug menu
- Fixes some mistakes

### CODE REVIEW

**Review by lewri — APPROVED** [review]
Thank you :)

**Comment by Matroftt** [comment]
Can someone reopen this pr please? I translated new strings that were added in 0.68 commits and I'm gonna turn it into wip until 0.68 beta or something

**Comment by lewri** [comment]
> Can someone reopen this pr please? I translated new strings that were added in 0.68 commits and I'm gonna turn it into wip until 0.68 beta or something

This PR was merged. You'll need to submit a new PR with any new text updates now.

**Comment by Matroftt** [comment]
> > Can someone reopen this pr please? I translated new strings that were added in 0.68 commits and I'm gonna turn it into wip until 0.68 beta or something
> 
> This PR was merged. You'll need to submit a new PR with any new text updates now.

Oh okay

**Pull request merged**
