### PR TITLE
Some small updates for the German language file

### PR DESCRIPTION
**Pull request by bobcanthelpyou**
First i wanted to update the `drug_improved_1` string, only

There was a `%1` used instead of a `%s`

bildschirmfoto vom 2015-07-26 01 38 20

But i updated some other stuff, too

### CODE REVIEW

**Comment by bobcanthelpyou** [comment]
override string `graphs.deaths` cause of

bildschirmfoto von 2015-08-01 19 13 41
to
bildschirmfoto von 2015-08-01 19 13 41

Override string `drug_improved` cause of wrong spelling

**Comment by Alberth289346** [comment]
Changes seem ok to me

**Comment by TheCycoONE** [comment]
@bobcanthelpyou do you know how to squash these changes into one commit, or would you like me to do it?

**Comment by bobcanthelpyou** [comment]
Are several commits in one pull request a problem? Why should these commits need to be squashed? And how to do that? I never done something like that before.

**Comment by wolfy1339** [comment]
git rebase -i HEAD~2
once the text editor shows up, change all the pick's except for the first one to s.

http://git-scm.com/docs/git-rebase

**Comment by bobcanthelpyou** [comment]
@Alberth289346 helped me to squash my commits and fix some other issues i had with git, i messed it all up, but i hope everything is fine now :)

**Pull request merged**
