### PR TITLE
[WIP] Multi os Travis.yml

### PR DESCRIPTION
**Pull request by tobylane**
This adds Mac testing, and the builds are usable by people who don't have the dependancies. Despite what it says on http://docs.travis-ci.com/user/multi-os/ apparently they are accepting requests by email, which is required for both parts to run at once. The first commit (plus later changes), the one to pull, uses cpp language and only linux is built, the second uses objective c language and only mac is built.

The only changes I made to the linux build were to add README.txt LICENSE.txt CONTRIBUTING.txt and changelog.txt, and put linux at the end of the zipname.

Another option is to have a mac only travis.yml in a branch which would be checked before releases.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Thanks for this @tobylane, OSX nightlies could be nice to have.
I'll list my biggest concerns here before looking at the changes more closely:
* Throughout the script you refer to the existing travis-ci build as "linux" but that's not a very accurate description of what is actually a cross compile to mingw (windows). In CorsixTH/deps I have called that travisci-mingw.
* There is a maintenance burden to travisci scripts, and none of the core developers use OSX. We would need ongoing commitment from you to maintain this if we are going to accept it.
* The first couple commits failed to build, before this is merged it should be reorganized so that every commit results in a successful build; presumably the 'fix' commits could just be squashed into the earlier commits.

**Comment by TheCycoONE** [comment]
I'm mostly fine with using $TRAVIS_OS_NAME, but not when it comes to the resulting zip file because in that case it's misleading to the people who will be downloading it (http://www.armedpineapple.co.uk/cth/builds/)

@alanwoolley do you have any concerns about pushing OSX builds to your server?

**Comment by alanwoolley** [comment]
> @alanwoolley do you have any concerns about pushing OSX builds to your server?

That's absolutely fine.

**Comment by TheCycoONE** [comment]
I think some more symmetry between the 'linux' and 'osx' code would be helpful, for instance the linux cmake and make are in the .travis.yml script, but the equivalents for osx are in the osx_install script.

`linux_scripts` could be called something like `build_cross_platform_targets` to more accurately describe what it does.

**Comment by tobylane** [comment]
The ifs need to be linux, I've changed all other references to mingw, and the OS in the zipname to windows.

I can commit to that. It is building for OSX 10.9 with Lua 5.1, the newer versions (OSX 10.10, Lua 5.2, Lua 5.3) all work within this script. The only other possible complication I could expect is differences between gcc and clang, which is unlikely and would be widely known.

Luac and Luarocks are supposed to have version independent paths like linux, they do on my system and on the linux. I added in ln to do that.

I kept the linux cmake and make in the section they were previously in but I'll switch to symmetry.

**Comment by wolfy1339** [comment]
I think you did something wrong here.
You probably meant to rebase the upstream master branch onto your branch and not merge it.
I would create a new branch and then cherry-pick the commit into the new branch and start over the pull request

**Comment by tobylane** [comment]
Sorry for the reopening, an unexpected outcome of rebasing.

Brought up to date and re-tested.

**Comment by tobylane** [comment]
Changes per requests (moved docs upload to cross platform scripts, fixed whitespace, added the extra upload to commit message).

**Comment by TheCycoONE** [comment]
As can be seen in the travis failure, the upload of the docs (which shouldn't have been triggered to start with) failed to authenticate.

**Comment by tobylane** [comment]
The sshpass commands are unchanged, so I suspect the error is because Travis doesn't decrypt the variable in forks and PRs, but that if statement can be triggered by PRs.

**Comment by alanwoolley** [comment]
@tobylane Yes, it can only be decrypted for builds triggered by the CorsixTH/CorsixTH repo so PRs will not get uploaded. The way to test this would be to merge in to a branch on CorsixTH/CorsixTH temporarily.

**Comment by TheCycoONE** [comment]
The line in question was:
``` if [ $TRAVIS_REPO_SLUG == "CorsixTH/CorsixTH" -a $TRAVIS_BRANCH == "master" ]; then sshpass -p "$SCP_PASS" scp -r -v -P12349 $TRAVIS_BUILD_DIR/fresh/doc/* cthbuilder@server2.armedpineapple.co.uk:/home/cthbuilder/docs/; fi; ```

which shouldn't be triggered for a PR, so I don't know why it was trying to upload in the first place - unless there was an accidental setting of TRAVIS_REPO_SLUG somewhere or the environment in scripts is different?

**Comment by TheCycoONE** [comment]
Perhaps try /bin/test syntax, something like:
```[ "$TRAVIS_REPO_SLUG" = "CorsixTH/CorsixTH" -a "$TRAVIS_BRANCH" = "master" ];```

**Comment by TheCycoONE** [comment]
@tobylane are you still interested in fixing this?

**Comment by tobylane** [comment]
Problem a) I am using master branch in my fork, and the travis way of doing things means it is both in master branch and in CorsixTH/CorsixTH despite only being a PR. The same commit, d6866b5, passes in tobylane/CorsixTH, https://travis-ci.org/tobylane/CorsixTH/builds/75924603.

Problem b) As identified by you and issue #879 this doesn't include dependancies. I believe @darrylblake or @admdly know something helpful.

**Comment by tobylane** [comment]
Closing in favour of an upcoming PR on Azure Pipelines.

**Pull request closed without merging**
