### PR TITLE
Typo in french version of the installer

### PR DESCRIPTION
**Pull request by mioux**
*Fixes #*

Nothing

**Describe what the proposed change does**
- Typo in a string in french installer

### CODE REVIEW

**Review by lewri — APPROVED** [review]
Yes, we're all too old here to dab. >.>

**Comment by lewri** [comment]
@TheCycoONE could we try and get the travis check re-run on this? Though given one word in a string is changed I doubt it actually could fail.

**Comment by TheCycoONE** [comment]
Please don't make pull requests from master.

**Comment by TheCycoONE** [comment]
I can't trigger this build in travis since it never came in at all 😦

**Comment by lewri** [comment]
Re-raised on 1713

**Comment by mioux** [comment]
Sorry, I did like I do on other projects I follow 😭

Thanks for the correction

**Comment by lewri** [comment]
Not to worry. Thanks for helping 😸

**Pull request closed without merging**
