### PR TITLE
[RDY] Bump travis to Xenial

### PR DESCRIPTION
**Pull request by TheCycoONE**
Trying to fix broken Travis builds

### CODE REVIEW

**Comment by mugmuggy** [comment]
This on upstream https://github.com/brunoos/luasec/issues/136

**Comment by TheCycoONE** [comment]
> This on upstream [brunoos/luasec#136](https://github.com/brunoos/luasec/issues/136)

Sounds relevant, bumping to xenial.

**Comment by TheCycoONE** [comment]
Bingo, just need ant because it's not included by default anymore.

**Comment by wolfy1339** [comment]
Any particular reason to still install GCC 5?

**Comment by TheCycoONE** [comment]
@wolfy1339 no, it's default anyway, but it doesn't hurt either right?

**Comment by TheCycoONE** [comment]
Removed explicit gcc version per @wolfy1339 's recommendation.

**Pull request merged**
