### PR TITLE
Improvements for ChrizmanTV Campaign Levels

### PR DESCRIPTION
**Pull request by Matroftt**
* Relates to #2675 

**Describe what the proposed change does**
- Makes HospitalValue criteria less for specific levels
- Some levels warn player about 10% or more death percentage, not 0%
- Fixes Upper Pukington flags

### CODE REVIEW

**Comment by lewri** [comment]
Your edits to the level file appear to have suspiciously affected every line with whitespace changes of some kind. Are you able to check that?

**Comment by Matroftt** [comment]
> Your edits to the level file appear to have suspiciously affected every line with whitespace changes of some kind. Are you able to check that?

Yes, they are showing as new for some reason, even if i paste unchanged .level files (royalhospital.level is an example)
I thought that it was a problem of encoding - but no, I tried unicode, utf8, ansi, iso-8859-1 but they all are still showing new strings in github
Sorry for creating commit mess, i made a big mistake while testing encodings

**Comment by lewri** [comment]
In that case it's probably fine. I'll leave it to @TheCycoONE just to double check (could well be some strange github bug)

**Comment by TheCycoONE** [comment]
No they're actually different. Will need to inspect.

**Comment by lewri** [comment]
> No they're actually different. Will need to inspect.

Git bash isn't giving me many clues, it believes they could be the same:
```yaml
$ file dethsdaw.level "dethsdaw (2).level"
dethsdaw.level:     ASCII text, with very long lines (456), with CRLF line terminators [original file]
dethsdaw (2).level: ASCII text, with very long lines (456), with CRLF line terminators [PR file]
```

**Comment by ARGAMX** [comment]
> Levels are still Line ending broken. @TheCycoONE are you able to push a fixed commit via your git so we can merge?

I will help to @Matroftt with this.

**Comment by tobylane** [comment]
Sorry, that was meant to be a fix but it wasn't so I rolled back.

**Comment by tobylane** [comment]
Fixed the whitespace, and a strange apostrophe in wishinwell.level. The original changes, minus whitespace, are here https://github.com/CorsixTH/CorsixTH/compare/master...Matroftt:fb3e34c93fb75c711e892f4f6b68871c529c5ef3?w=1

**Comment by Matroftt** [comment]
Thanks Toby

**Pull request merged**
