### PR TITLE
Fix various grammar issues in README.md

### PR DESCRIPTION
**Pull request by wolfy1339**
Fix README.md

### CODE REVIEW

**Comment by TheCycoONE** [comment]
There are quite a few grammar errors in that block of text too. I don't suppose you feel like cleaning up more of it?

**Comment by wolfy1339** [comment]
I will look at that later

**Comment by corsix** [comment]
I actually care a lot about grammar and about the correct capitalisation of Lua, so :+1: from me, merging. (Who knew I had merging rights on GitHub?)

**Comment by TheCycoONE** [comment]
/me considers revoking CorsixTH commit rights from @corsix. j/k, good to see you're still lurking!

**Pull request merged**
