### PR TITLE
Remove tabs from code

### PR DESCRIPTION
**Pull request by lewri**
*Fixes https://github.com/CorsixTH/CorsixTH/pull/2276#pullrequestreview-1155573601*

**Describe what the proposed change does**
- Replaces tabs with 2 spaces as documented.

### CODE REVIEW

**Comment by lewri** [comment]
@TheCycoONE can we add a unit test to github actions to check for tabs?

**Comment by tobylane** [comment]
That was the purpose of this line, but it doesn't work as intended. https://github.com/CorsixTH/CorsixTH/blob/54c0adc37caa612bd9e154f5f56958cc87ec57e9/.github/workflows/Linux.yml#L104

I think this is a suitable replacement - IPRn are ignore binary files, recursive into directories, Perl regex and give line numbers. `grep -IRPn '\t' CorsixTH/Lua CorsixTH/CorsixTH.lua`.

**Comment by lewri** [comment]
> That was the purpose of this line, but it doesn't work as intended.
> 
> https://github.com/CorsixTH/CorsixTH/blob/54c0adc37caa612bd9e154f5f56958cc87ec57e9/.github/workflows/Linux.yml#L104
> 
> I think this is a suitable replacement - IPRn are ignore binary files, recursive into directories, Perl regex and give line numbers. `grep -IRPn '\t' CorsixTH/Lua CorsixTH/CorsixTH.lua`.

Not fully convinced languages should be excluded. Feed bad practice anywhere and it'll creep to other areas :( .

**Comment by tobylane** [comment]
Yes, as here you make the changes needed we can stop excluding it.

**Pull request merged**
