### PR TITLE
Chinese updates by lokpro

### PR DESCRIPTION
**Pull request by Alberth289346**

### CODE REVIEW

**Comment by Alberth289346** [comment]
From https://github.com/CorsixTH/CorsixTH/pull/2276#issuecomment-1289951636 where lokpro announced existence of the updates.

@lewri Nothing git magic needed, just a pull request from lokpro master to corsix master

**Review by lewri — APPROVED** [review]
I believe the original request was to go into the other PR as it sat inside its scope. But this is fine too.

**Comment by Alberth289346** [comment]
Oh, missed that, sorry.

**Comment by TheCycoONE** [comment]
Are we holding off for more changes? I don't mind merging as is

**Comment by lewri** [comment]
Nope it can go in , didn't get any other translators take a bite

**Pull request merged**
