### PR TITLE
Only remove fax messages relating to local humanoids

### PR DESCRIPTION
**Pull request by tobylane**
**Describe what the proposed change does**
- Only remove faxes (ui) of local patients/staff.

### CODE REVIEW

**Comment by tobylane** [comment]
It's a strange one, it belongs with the action and the patient, but as ui it should be put with the player parts, like the creation of these faxes has been.

**Comment by Alberth289346** [comment]
Lewri:
I  saw this change, and I also considered it weird. However, I also know that our actions do all kinds of weird things like creating faxes as Toby said, so I can fully understand where this is coming from.

Since having it hidden in an action is probably less desirable than having it in the hospital, I'd consider the move an improvement. The fact it's weird suggests that it is probably not the final spot for this code.

**Comment by lewri** [comment]
Cool.. All good with me then.

**Comment by TheCycoONE** [comment]
yeah I get it, with all player specific things going through player_hospital vs hospital.

**Pull request merged**
