### PR TITLE
[RDY] Code reformatting to code style

### PR DESCRIPTION
**Pull request by Alberth289346**
- Adding spaces around operators
- Change indenting of multi-line, or fix bad indenting
- Moving operator to end of previous line

### CODE REVIEW

**Comment by Alberth289346** [comment]
Updated, fixed all points, except the "spawn points" comment (in World:spawnVIP), the line was a literal duplicate of the line about 10 lines down, first use is at about 11 lines down.

**Comment by TheCycoONE** [comment]
Curious about the appveyor failure, I don't even see the build, and it doesn't help that the error is cut off.

**Comment by TheCycoONE** [comment]
Just waiting for #933 to drop because I think it will be easier to fix conflicts here than there.

**Comment by TheCycoONE** [comment]
@Alberth289346 could you rebase this on the latest master. I'll merge now since drug casebooks is delayed again.

**Comment by Alberth289346** [comment]
rebased

**Pull request merged**
