### PR TITLE
Add Animview, 32bit, pr checkout on demand to Windows Actions

### PR DESCRIPTION
**Pull request by tobylane**
**Describe what the proposed change does**
- Add on demand builds, with options for 32bit, Animview builds, of a specific pr. Here's a 32bit build with Animview of 2489 (a recent PR with cpp changes) https://github.com/tobylane/CorsixTH/actions/runs/7934724743/job/21666299492
- Name the output
- Update old steps

### CODE REVIEW

**Review by lewri — COMMENTED** [review]
Not against 32 bit being still feasible as long as it doesn't have any limitations for us in future

**Comment by TheCycoONE** [comment]
This is going to conflict with my PR

**Comment by TheCycoONE** [comment]
Much of it should be redone to use cmake presets and the vcpkg addon. Building all three of the presets i added plus installing doxigen and either lua/lfs or using the vcpkg version like i did with appveyor

**Review by TheCycoONE — CHANGES_REQUESTED** [review]
Needs to be updated to take advantage of the cmake --prefix options that I added and the new vcpkg mechanics.

**Comment by tobylane** [comment]
Added a configure-only step for win-dev. Lfs, etc are included. Do you want docs built on windows?

[x86 run](https://github.com/tobylane/CorsixTH/actions/runs/8400619622/job/23008097759), [recent win-dev run](https://github.com/tobylane/CorsixTH/actions/runs/8400445325).

**Comment by TheCycoONE** [comment]
I don't think we need docs here, as we have them in the linux action. Merged.

**Pull request merged**
