### PR TITLE
[RFC] Make WindowsInstaller test for 2017 Redistributable

### PR DESCRIPTION
**Pull request by TheCycoONE**
The Visual C++ Redistributable for Visual Studio 2017 is a bit different than
2015. The installed key doesn't tell us that we are using the right one because
both 2015 and 2017 install to the 14.0 path. 2017 is backwards compatible and
registers itself with the version 14.10.#####

### CODE REVIEW

**Comment by wolfy1339** [comment]
It seems you reset all localization to English. Would it not be possible to only change 2015 to 2017 using a simple find and replace? As to not replace the localized text

**Comment by TheCycoONE** [comment]
I didn't realise any of them were actually translated. It seems only French was, so I will restore it. The rest have the wrong English name, so replacing the number isn't sufficient.

**Comment by TheCycoONE** [comment]
@Lego3 there is no good landing page anymore. You get it from here: https://www.visualstudio.com/downloads/ which I consider a little overwhelming.

You're right about the architecture issue. I used the 'bookmark' link from that page, which wasn't updated whether I selected x64 or x86. I thought it might be using some sort of host detection to serve the appropriate file but that looks not to be the case. I can fix it to link to the appropriate file; or we can make our own landing page and link there?

**Comment by wolfy1339** [comment]
I did find this, it is some sort of a landing page: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by TheCycoONE** [comment]
@wolfy1339 that page also appears to only link to the x64 version?

**Comment by wolfy1339** [comment]
Would this be what were looking for: https://www.visualstudio.com/downloads/#other

**Comment by TheCycoONE** [comment]
Yeah, I think that's friendly enough for now. Certainly better than the 0.60 approach (nothing, except a note in the release notes).

Thanks @wolfy1339

**Comment by TheCycoONE** [comment]
Pushed a couple changes to address the comments by @Lego3 and @wolfy1339 

Hopefully we can get more localizations done before the release.

**Comment by TheCycoONE** [comment]
@Lego3 do you think you'll have a chance to look at my fixes this week?

**Comment by Lego3** [comment]
Sorry, a little fast there on the merge. Should of course have squashed it. Getting rusty at this...

**Pull request merged**
