### PR TITLE
[RDY] Fix patient reserving doors

### PR DESCRIPTION
**Pull request by mugmuggy**
Hopefully thisis a suitable refactor as mentioned in #1453
Addresses my comment in #1561 with saved_must_happen not existing, and therefore must_happen not being correctly set.

Patients holding reservations on doors (#1081), reserve_on_resume needs to be copied, as this was not copied to the requeued walk action, the interrupt handler, would not unreserve the door, when interrupting walk action. This is brought about for drinks machine (and would be for falling) as action.keep_reserved is set to true, which bypasses the door unreserve logic.

Then as it wasn't copied, if they were interrupted again, the door would remain reserved.

### CODE REVIEW

**Comment by mugmuggy** [comment]
I've got some checks sitting in some code that I need to validate are actually required for this and the other PR, they might have just been related to trying to avoid warnings printed from leaving queue actions as well.

**Comment by TheCycoONE** [comment]
Ok. Well I am good with landing this one when you are ready.

**Comment by mugmuggy** [comment]
In #1081 I made the note of preventing the drinks machine use if reserve_on_resume was set. However I did quickly check TH and managed to witness, a patient popped from start of queue, make their way to the drinks machine before entering room, so this seems a possibilty.

This last change ensures that if the walk after leaving queue, into the room after the reservation is made is interrupted for drinks machine use as an example, then whilst the patient is using the drinks machine, they are evacuated/kicked etc, that the walk action into room will be interrupted and not just removed via setNextAction.

**Comment by mugmuggy** [comment]
That last change is defective in particular scenarios and am exploring another option.

**Comment by mugmuggy** [comment]
Corrected the issue with the code originally with #1568

**Pull request merged**
