### PR TITLE
[RFC] UIJukebox prevents save due to persistance error if open at time of save

### PR DESCRIPTION
**Pull request by mugmuggy**
An attempt to address #1385

### CODE REVIEW

**Comment by Alberth289346** [comment]
A layer woven into the entire program to fix the broken persistence?

**Comment by TheCycoONE** [comment]
Not sure what you mean here @Alberth289346 

The issue is that info is a C++ object not a lua object, and doesn't have the prerequisite methods defined on it to be able to be persisted.

This PR doesn't address that directly, instead removing info from the persist list. In truth we don't want UIJukebox persisted at all.

To summarize: this PR is not the fix we want for this issue. The question is whether the new code is cleaner and should be merged, or is messier or just as messy and should be rejected independent of being a workaround for the bug at hand. I haven't decided yet.

**Comment by TheCycoONE** [comment]
This PR is cleaner than without it in my opinion and should be merged.

**Comment by TheCycoONE** [comment]
@mugmuggy are you ok with this being merged (RDY)? I still think it would be best not to persist the dialog, but I like this change too.

**Comment by mugmuggy** [comment]
Yep

**Pull request merged**
