### PR TITLE
[WIP] Implementing AI Hospitals

### PR DESCRIPTION
**Pull request by mugmuggy**
I mentioned this branch in #967 but thought I would include it here for some more visibility, whilst I fine tune some more aspects. Happy to receive any comments but I do intend to update and tweak until I'm satisfied and make it RFC.

### CODE REVIEW

**Comment by altiereslima** [comment]
Works fine

**Comment by Alberth289346** [comment]
Nice!
I think you should start by taking unrelated (like annual report), and somewhat related (refactoring existing hospital/etc code) changes out of this, and make them their own small PRs.

That way, you improve the existing code, and pave the way for adding the AI hospital.

**Comment by mugmuggy** [comment]
That was the plan originally, I think I started putting some comments on some existing issues as well for that plan to be realised. Just if you had the other changes missing the corrupted annual report screen wouldn't make for a nice comparison for demonstration purposes and tuning the spawn logic was also done for comparison sake here.

**Comment by lewri** [comment]
@mugmuggy wondering how the state of play is with this now? Alberth laid down new player hospital and ai hospital foundations, so imagine some things would need moving about here too.

**Comment by lewri** [comment]
Unlinked from issue for now. Closing PR until mugmuggy's return or another adopter wishes to take this over (activity idle for near 6 years).

**Pull request closed without merging**
