### PR TITLE
typos

### PR DESCRIPTION
**Pull request by a-detiste**
This doesn't impact translated strings at all;
mostly code comments/README/& one error message.

But now the next time someone runs "codespell"
he'll find important typos faster.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
:+1:

**Comment by Alberth289346** [comment]
The Doxygen files typos come from the doxygen program upstream. Better not change that, as the next update will revert the change.

**Comment by a-detiste** [comment]
It has been fixed in Doxygen on 2014/1/12

https://github.com/doxygen/doxygen/blob/master/src/config.xml#L3021

https://github.com/doxygen/doxygen/commit/4b51e6113f1e9e20a5700840d83f1c3928d84825

**Comment by Alberth289346** [comment]
great, thanks for checking it out.

**Pull request merged**
