### PR TITLE
[ready] Rewrite actions to use construction functions

### PR DESCRIPTION
**Pull request by Alberth289346**
New attempt of #1019 hopefully better for reviewing.

Compared to the previous attempt, things have less clutter, the "split function" commits are best reviewed using a whitespace ignore on the diff,
Ran a test on an old level 1 and level 4 save game, and that seems to run fine.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Verified by visual inspection up to ec0b4f025ee

The following commit uses ```enableTreatmentRoo``` is there justification for why you use enable here and set for others e.g. ```setMustHappen```

**Comment by TheCycoONE** [comment]
Maybe ```setIsTreatmentRoom```, taking an optional bool for consistency? The rest of that commit looks good.

**Comment by TheCycoONE** [comment]
For SpawnAction in d1ea6253af0efe8e620f2421d23973cd1f84b19c I think point is required but you include setPoint rather than putting it in the constructor. My understanding is that required fields go in the constructor (which would make it easier to add verification in the future).

**Comment by TheCycoONE** [comment]
Visually reviewed up to 2d4aceaf511c015 inclusive.

**Comment by TheCycoONE** [comment]
In 3ddeedee057 seek_reception.lua setMustHappen is set to true instead of action.must_happen

**Comment by TheCycoONE** [comment]
684cc7e32 and 06e20d9de look ok to me in kdiff3

**Comment by Alberth289346** [comment]
> The following commit uses enableTreatmentRoo is there justification for why you use enable here and set for others e.g. setMustHappen

The rule is: "setXYZ" takes a value, "enableXYZ"/"disableXYZ" does not. Before, I had some "setXYZ" with a value, and some "setXYZ" without value, which was too confusing, so I renamed the ones without value. Taking or not taking a value is mostly determined by whether the property is ever given at least more than a single value, although it possible I missed some case there.

> Maybe setIsTreatmentRoom, taking an optional bool for consistency?

I had that at some point, but then you have these property setters that only ever assign "true", which looks silly too (in particular with properties used in the negative sense "setNoWait(true)"-like calls).

> My understanding is that required fields go in the constructor

That is the intention indeed

**Comment by Alberth289346** [comment]
Updated the branch:

- Added the setPoint() property into the SpawnAction constructor (spawn rewrite)
- Fixed the "action.must_happen" in seek_reception (queue rewrite)
- Fixed two typos found by luacheck diff (use_object rewrite)
- Fixed the doc problem (spawn rewrite)

**Comment by TheCycoONE** [comment]
Right, I've seen other enable/disable flags now so that's alright. enableTreatmentRoom still sounds weird to me for a flag that advises that the target room is for treatment but I can live with it. The flag name predates this pr.

**Comment by TheCycoONE** [comment]
Commit message typo in 5eefb3d bood to blood.

**Comment by TheCycoONE** [comment]
6ebf067 results in incorrect indentation for queuing sink action. Maybe fixed in later commit?

**Comment by TheCycoONE** [comment]
Visual review up to b7fbd264 exclusive. Have not gone back to changes yet.

**Comment by Alberth289346** [comment]
Queueing sink action gets completely rewritten in 'use object rewrite' in commit 141517c, resolving the indent problem

**Comment by TheCycoONE** [comment]
b7fbd2643ac29f1d8f443ef42d73267a693b3eb9 changes the function signature for the loop_callback function to take the action as an argument instead of a closure. A quick grep of the code shows that some actions call loop_callback passing in the action and some do not.

I'm not saying it's wrong, but it is suspicious.

**Comment by TheCycoONE** [comment]
In the use_object commit, calling setWateringPlant with no argument sets it to nil not true. It is called with no argument in plant.lua.

Maybe should use enable style here?

Additionally lots of action properties were not converted to methods. Is than an oversight or justified?

**Comment by TheCycoONE** [comment]
Also use_object. In dna_fixer ```setProlongedUsage``` is called with no argument. Should be called with ```false```

**Comment by TheCycoONE** [comment]
In ward.lua setProlongedUsage is called without argument for true, but the function is not defined that way.

**Comment by TheCycoONE** [comment]
For multi_use rewrite, again setProlongedUsage does not set to true with no argument. Called that way in place of true frequently. Not listing them here.

**Comment by TheCycoONE** [comment]
In cardiogram.lua loop_callback function name does not match in diff

**Comment by TheCycoONE** [comment]
Use_object and multi call setNoTruncate. Function is disableTruncate

**Comment by TheCycoONE** [comment]
With respect to the loop_callback argument above, it looks alright in this case. Two caveats are that in meander the loop_callback is called without providing the action, and in idle_spawn, the callback is copied from another action so the argument would be different than the closure. It doesn't look like either of those can come up as a result of a use_object action.

**Comment by TheCycoONE** [comment]
Sometimes a temporary is introduced to split lines and sometimes the next method in the chain is just placed indented on the next line. I prefer this method if we are not otherwise using the action variable. Can point them out inline if you like.

**Comment by Alberth289346** [comment]
Fixes:
- walk rewrite: ": continuation lines"
- queue rewrite: ": continuation lines"
- split function from cardiogram... : fix cardiogram loop_callback function name
- split function from blood room... : fix commit message typo
- split function from toilets action...: Did not fix incorrect indent, it's not fatal, and gets removed further in the queue anyway
- use_object rewrite:
  * Use enableWatering as property instead of setWatering
  * ": continuation lines"
  * setProlongedUsage() argment fixes
  * use disableTruncate everywhere
- multi_use rewrite:
  * setProlongedUsage() argment fixes
  * use disableTruncate everywhere
  * add setLayer3 property method
- futher enhancements: Small action simplifications with action properties not noticed before

**Comment by TheCycoONE** [comment]
Further enhancements isn't a descriptive commit message, but it looks like it can be squashed into *walk rewrite*

**Comment by TheCycoONE** [comment]
Re-reviewed up to *seek staffroom rewrite*, all looks good so far.

**Comment by TheCycoONE** [comment]
Reviewed up to *walk rewrite* exclusive. Please do the suggested rebase before I continue. sha-1s won't change up to f0456ce037 and I can then only look at 'final' commits.

**Comment by Alberth289346** [comment]
merged the 'further enhancements' into the walk rewrite, thanks for all your efforts here

**Comment by spinktvis** [comment]
Hi Albert, after trying the latest AppVeyor build i discovered that there is a double colon on line 56 of multi_use_object.lua. After removing it it is running fine. 

+function MultiUseObjectAction::setLayer3(layer3)

**Comment by Alberth289346** [comment]
Clearly a case of writing too much C++ :)
Thanks for finding, fixed it.

**Comment by TheCycoONE** [comment]
Typo in walk rewrite, scanner_room. *diableTruncate*

**Comment by Alberth289346** [comment]
Fixed typo "diable" -> "disable", and reverted the accident (looks like git tried to be too smart in applying a patch at first sight)

**Comment by TheCycoONE** [comment]
Reviewed all action rewrite commits. I need to go back and look at the split commits again.

**Comment by Alberth289346** [comment]
Fixed the messed up loop callback, the original inline persistable function line was not replaced with the newly introduced loop_callback_training variable.

Diff between new head and the previous head is empty, ie no changes got introduced in the final rewrite result.

**Comment by TheCycoONE** [comment]
All LGTM. Still going to test.

**Comment by Alberth289346** [comment]
\o/

**Pull request merged**
