### PR TITLE
[RDY] Actions - Linux and tests

### PR DESCRIPTION
**Pull request by tobylane**
**Describe what the proposed changes do**
- Removes the date and doxygen version in docs. It means updates to the docs are actual content updates only.
- A few more codespell changes
- Move to Github Actions. There's several ways to do this, eg making more use of other actions for cmake.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Can you leave in .travis.yml for now. It needs to be disabled on the project before/if the file is removed.

**Comment by TheCycoONE** [comment]
I like the extra lint, e.g. cmakelint, as well as the gh-pages documentation!

**Comment by TheCycoONE** [comment]
luaJIT goes deeper than the lua, we also want to verify the full build with the 5.1/luajit includes. I think it warrants a build matrix, or possibly a second pipeline; but that can certainly be future work.

**Comment by tobylane** [comment]
Added the matrix and travis.yml.

**Comment by tobylane** [comment]
Fixed the Luajit build.

**Comment by TheCycoONE** [comment]
Not sure where my review went - but it looks good to me!

**Review by TheCycoONE — APPROVED** [review]

**Comment by TheCycoONE** [comment]
Anything else you're waiting for @tobylane - I would like to merge this as is.

**Comment by tobylane** [comment]
Good to go.

**Comment by tobylane** [comment]
Can you make an orphan gh-pages branch and add an empty .nojekyll file, then rerun the failed job. Sorry, should have mentioned this before.

**Pull request merged**
