### PR TITLE
[RDY] Pathfinding broken by side objects

### PR DESCRIPTION
**Pull request by mugmuggy**
A proposed resolution to #1105 and related issues where pathfinding breaks from placement of side objects.

afterLoad in map and world to call their required methods to fix pathfinding on old saves.

To prevent the issue occuring, added a check and calls to those same functions in Object:onDestroy after the super class method is called when any side objects are moved.

### CODE REVIEW

**Comment by mugmuggy** [comment]
This is ready, not sure why Appveyor idn't pick it up and report it back. But as this is a lua change only should be ok, to take the travis-ci as an indicator its passing.

**Comment by MarkL1961** [comment]
@mugmuggy  I could be wrong, but I think you need to update app.lua to `local SAVEGAME_VERSION = 118` as the current save game is 117 (I got this from the last build on appveryor)
Otherwise your afterload won't work as intended.
@TheCycoONE might do this at the merge stage, as it can be difficult to keep track if merges are done out of order

**Comment by TheCycoONE** [comment]
I'd rather the version was bumped here, if it's out of order I'll get a merge conflict and can fix it. If it's not there at all I could miss it.

**Comment by TheCycoONE** [comment]
There are hard coded litter check at:
* https://github.com/CorsixTH/CorsixTH/blob/fa0ae5362fdf1ac115d84b817513225cb75686c8/CorsixTH/Lua/dialogs/edit_room.lua#L1150
* https://github.com/CorsixTH/CorsixTH/blob/fa0ae5362fdf1ac115d84b817513225cb75686c8/CorsixTH/Lua/world.lua#L2721

The first one is almost an identical check to what you're doing here (though it doesn't also check rat tiles, which may be a bug.) As well these are the only place isTileExclusivelyPassable is called on. I would prefer you remove the redundant checks, if you must keep checks for particular object numbers instead of flags, put them in one function (e.g. isTileExclusivelyPassable), and preferably use another object property besides it's thob.

**Comment by mugmuggy** [comment]
Litter has no footprint, so getWalkableTiles will be called, so with this check in isTileExclusivelyPassable, I'm basically saying ignore checking litter - which really means check for doors in object placement and check doors for opposing entrances in room construction. Could guard the for loop with an if statement checking if the type is litter to make it a little more obvious that we don't want to do it.

Rathole has an empty footprint table so basically skips over the first loop in isTileExclusivlePassable and a door can't be placed on an existing wall so not required in edit_room.

The check in edit_room you've highlighted, is to prevent say the drink machine actual tile, blocking a door and object physically in front of it,  the isTileExclusivelyPassable checks only the passable tile of the drinks machine is also not blocking the door. And there is the same process in placing an object. In Place Object I check to ensure that the only object on the tile is currently litter/rathole and if so check passable tiles of nearby objects.

**Comment by TheCycoONE** [comment]
Some day I hope for a cleaner fix for this.

**Pull request merged**
