### PR TITLE
Updating Spanish translation

### PR DESCRIPTION
**Pull request by IlDucci**
Fixing things and removing strings that were removed in the English text.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Is the final result what you want; just asking because of the revert and the revert revert commits.

**Comment by TheCycoONE** [comment]
I see there is no difference between your first commit and your last one, so I guess the revert was accidental?

**Comment by IlDucci** [comment]
Yes, sorry, I was testing the Windows client and I messed up quite a bit. There was a double revert.

**Comment by TheCycoONE** [comment]
It appears that these changes were made against an old version of CorsixTH. The only changes to the current master I see in your pull request is removing end_month and end_year.

**Comment by IlDucci** [comment]
That's likely. I'm still trying to get used to Github for Windows. If the new strings are synched with the English ones, this can be closed.

**Comment by bobcanthelpyou** [comment]
@IlDucci Could you also check the 'Dump Strings' tool within the game (in the debug menu under 'VOLCAR TEXTOS DEL JUEGO')? It complains about the following missing strings:

menu_debug.connect_debugger
fax.vip_visit_result.remarks.very_bad[1]
fax.vip_visit_result.remarks.very_bad[2]
fax.vip_visit_result.remarks.very_bad[3]

**Comment by IlDucci** [comment]
OK; strange that those were gone, my copy had them. Anyways, I've updated the Spanish file with a lot of changes and fixes to the original translation.

**Comment by TheCycoONE** [comment]
Changes were merged.

**Pull request closed without merging**
