### PR TITLE
[rdy] Order of the sliders could make the 'guess_cure' slider unusable.

### LINKED ISSUE #1174: diagnosis procedure sliders getting stuck in hospital policy screen (F9)
#### Describe the issue

In the hospital policy screen (F9) under diagnosis procedure when the 'send home' and 'guess at cure' slider are close the 'send home' slider can no longer be moved. As the 'guess at cure' slider can only be moved to the right of the 'send home' button this results in the 'send home' slider getting stuck if both sliders are moved to the right.

#### Expected Behavior

Both sliders should be moveable even if they are in the same spot.

#### System Information
**CorsixTH Version:** 2fe2658da038a7537768c6b5e06cf03991715a52

**Operating System:**  Linux Debian Jessie

**Theme Hospital Version:** CD

### PR DESCRIPTION
**Pull request by Alberth289346**
Fixes #1174

### CODE REVIEW

**Comment by MarkL1961** [comment]
For me it now does not save your choice.
I move the sliders and the next time I open they are back in the default positions

**Comment by Alberth289346** [comment]
Thanks @MarkL1961, fixed that.
I also updated the patch for comments by @TheCycoONE

**Comment by Alberth289346** [comment]
And fixed again, please review

**Comment by Alberth289346** [comment]
Comment in the afterload fixed

**Comment by MarkL1961** [comment]
Works for me and fixes the save in the original issue

**Comment by Alberth289346** [comment]
Thanks for testing!

**Pull request merged**
