### PR TITLE
Fix case insensitive file selection in Animview

### LINKED ISSUE #1750: [Bug] AnimView File select OSX
#### Describe the issue
It's not possible to select `FONT00V.DAT` in AnimView's Sprite Viewer on OSX.

#### Steps to Reproduce
1. Open AnimView.app
2. Select Sprite Viewer
3. Try to open the FONT00V.DAT

#### Expected Behavior
`FONT00V.DAT` should be clickable and selectable in the OS File Dialog

#### System Information
**CorsixTH Version:** N/A

**Operating System:** *OSX 10.15*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt
N/A

### Additional Info
N/A

### PR DESCRIPTION
**Pull request by tobylane**
*Fixes #1750*

**Describe what the proposed change does**
- Use wildcards for file system case insensitivity in the Animview file select dialogs.

### CODE REVIEW

**Comment by lewri** [comment]
Can we close #1751 in favour of this?

**Comment by TheCycoONE** [comment]
Yes, seems reasonable. `.Dat` etc. should be rare to non-existent. Will test in Linux before merging.

**Comment by lewri** [comment]
@colinjmatt as our other Mac user does this work for you?

**Comment by Alberth289346** [comment]
What's wrong with `[dD][aA][tT]` notation? That should capture all upper/lower case combinations.

**Comment by tobylane** [comment]
That's not supported, the docs say just ?* https://wiki.wxwidgets.org/WxFileSelector

**Comment by Alberth289346** [comment]
No documentation about the `;`  ?

Note, it might be a good idea to copy those links into the code, for future reference.

**Comment by tobylane** [comment]
https://docs.wxwidgets.org/trunk/classwx_file_dialog.html This has a little more detail.

**Pull request merged**
