### PR TITLE
Prep for next prerelease

### PR DESCRIPTION
**Pull request by lewri**
Awaiting decision on if this will be Beta 2 or RC 1 (and a suitable period of test time)

### CODE REVIEW

**Comment by lewri** [comment]
@TheCycoONE are we going with Beta 2, and halting features after that? The features for Beta 1 probably need a short window to be set in.

**Comment by TheCycoONE** [comment]
RC1 is when I intend feature freeze.

**Comment by lewri** [comment]
> RC1 is when I intend feature freeze. I intend to go straight to it. We don't usually see much stabilization anyway

So format this one to RC1 year?

**Comment by lewri** [comment]
Updated to be RC1

**Comment by TheCycoONE** [comment]
```
appstreamcli validate --pedantic CorsixTH/com.corsixth.corsixth.metainfo.xml
✔ Validation was successful.
```

**Pull request merged**
