### PR TITLE
SDL 2: Renamed "enter" key character references to: "return"

### PR DESCRIPTION
**Pull request by J-Shep**
SDL 2 changed the name of this key from "enter" to "return" so
this commit updates references to this key's name.

### CODE REVIEW

**Comment by sgtbigman** [comment]
Guessing we'll want to eventually update Corsix's keyhandler to use SDL_Keycode Values so that this kind of issue is automatically handled.

**Comment by TheCycoONE** [comment]
This pull request doesn't handle updating save games.  I think it should be fine as long as no dialogs are open though?

**Comment by J-Shep** [comment]
>> This pull request doesn't handle updating save games.

@TheCycoONE I will add code for this.

**Comment by J-Shep** [comment]
I've pushed my latest code for this commit I will test it now.

**Comment by J-Shep** [comment]
I've tested the afterLoad() changes with each affected dialog with 0.40 saves and they all work except for the "edit room" dialog which crashes the game when return is pressed but this crash isn't being caused by my simple change because it also occurs in 0.40 when I try to load this 0.40 saved game (with its room blueprint & edit room dialog) and then press return to confirm the blueprint's shape phase.

**Comment by TheCycoONE** [comment]
Yes, the edit room bug is mine, which is why I thought to mention it. #605

**Pull request merged**
