### PR TITLE
[RDY] Remove very old debian packaging files?

### PR DESCRIPTION
**Pull request by Lego3**
The DebianPackage folder was something I did a few years ago as an exercise for myself that could possibly have been developed further. Since I knew almost nothing of best practices I would say that folder is mostly confusing. If someone decides to create packages for real that folder should not be the base.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
I've sent an email to our packager at playdeb to see if they use this at all. If they don't, then I agree to merge this.

**Comment by TheCycoONE** [comment]
The PlayDeb maintainer has gotten back to me. They have no use for this file, their build scripts are actually public here: https://github.com/ckorn/PlayDeb/tree/wily/corsix-th

**Comment by TheCycoONE** [comment]
@Lego3 are you ok if I merge this? (not marked as rdy)

**Comment by Lego3** [comment]
Sure. :-)

**Comment by a-detiste** [comment]
It's in Debian since yesterday.

It also turns out quite a lot of people was using this upstream-provided package;
but changed their mind when it became outdated.
(the ones with corsix-th but without platform-indepedant corsix-th-data)
https://qa.debian.org/popcon.php?package=corsix-th

**Pull request merged**
