### PR TITLE
[RDY] Implemented missing timer click behaviour. Fixes #882.

### LINKED ISSUE #882: Coundown timer left/right click functionality.
After flicking through the [TH Manual](http://imgur.com/KdSVIhk) (the paragraph in question is starred) I found that the countdown timer used on Emergencies and Epidemics has some hidden left and right click functionality not currently implemented in CorsixTH.

#### Emergencies:
Right clicking the timer brings up an emergency patient's* information panel (The same panel as a standard left click on a patient) Subsequent right clicks cycle through each emergency patient.
Left clicking centres the view on this patient, the patient centred on is dependant on the last right click.

#### Epidemics:
Epidemics are a little bit different, as right click *does not cycle though* patients. Right clicking only brings up one patient needed a vaccination*, even though there could be many patients needed Vaccination present in the Hospital.
Left clicking centres the view on this patient.

### In both instances:
* The first left click does nothing. (until you right click)
* Clicking the timer plays sound ~~[TYPING.WAV or XRAY2.WAV](https://github.com/CorsixTH/CorsixTH/wiki/Sound-List)~~, I can't quite tell which.

~~*As far as I can tell, the first patient chosen is the one nearest you at the time.~~

EDIT: The sound heard is CAMCLICK.wav, this is verified in the title field of the [Sound List](https://github.com/CorsixTH/CorsixTH/wiki/Sound-List).

### PR DESCRIPTION
**Pull request by sadger**
Needs confirming it works, have tested it a little myself already.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Is this ready now sadger?

**Comment by sadger** [comment]
No, not yet. The behaviour for epidemics needs changing based on some observations of the original. Will do it this weekend.

**Comment by TheCycoONE** [comment]
Ok, change the label to RDY when you're ready for code review again please.

**Comment by sadger** [comment]
Could do with a quick test slightly modified, didn't hear from @joewestcott about it again. But code is ready.

**Pull request merged**
