### PR TITLE
[RDY] Changes from clang tidy and format, codespell, cmakelint, and a luatest fix

### PR DESCRIPTION
**Pull request by tobylane**
**Describe what the proposed change does**
- The busted check currently only passes on 5.1. Is this change in the right place?
- Minor fixes from the tools used in the upcoming pipelines PR

### CODE REVIEW

**Comment by Alberth289346** [comment]
All the empty lines in the includes seem a bit silly, but otherwise looks good to me

**Comment by TheCycoONE** [comment]
Looks good to me. Some versions of clang-format want an empty line between the different categories of include - easier not to fight it.

**Comment by TheCycoONE** [comment]
@tobylane is this ready, I see no reason not to merge it.

**Comment by tobylane** [comment]
It's ready.

**Pull request merged**
