### PR TITLE
Issue #1251 - Final message too long in Spanish

### PR DESCRIPTION
**Pull request by AdamFx990**
https://github.com/CorsixTH/CorsixTH/issues/1251

The final message shown on game completion has been condensed a bit to fit onto the final screen. It probably can't be made much shorter removing some key information.

### CODE REVIEW

**Comment by sadger** [comment]
Looks good to me. Have you tested this fits on the dialog?

**Comment by AdamFx990** [comment]
Not yet, I'm at work at the moment so can't test for a few hours. It should
be fine though.

**Comment by sadger** [comment]
Great! Happy to merge as soon as it's confirmed.

**Comment by AdamFx990** [comment]
screenshot from 2018-03-23 20-10-05

**Comment by sadger** [comment]
Looks great! Thanks for the contribution.

**Pull request merged**
