### PR TITLE
Refactor clipping on render_target to keep a stack of clips.

### PR DESCRIPTION
**Pull request by flackr**
**Adds a clip stack on render_target which allows for temporarily adding and removing clips.**
- Since we never need to get the clip anymore, imprecision resulting from the scale factor no longer accumulates.
- Simplifies calling code as it doesn't need to explicitly remember the old clip and restore it.
- Adds a convenience class which automatically restores old clip when it goes out of scope.

### CODE REVIEW

**Comment by flackr** [comment]
@TheCycoONE I'm not 100% confident about the lua change as it required adding the new width accessor. What's the best way to test messages?

**Comment by TheCycoONE** [comment]
The clipping that was changed for UIMessage is while the fax icons scroll up before they scroll left on the bottom panel. It happens fairly quickly and is subtle so it can be hard to catch.

Starting from any save game, or start a new hospital and place the just a receptionist, desk, gp office, doctor, open the hospital and hold Z - a message will pop up sooner than later.

**Comment by TheCycoONE** [comment]
The clang complaint https://github.com/CorsixTH/CorsixTH/runs/6442929540?check_suite_focus=true#step:11:84 looks legit; you removed the get_clip_rect that was populating rcOld before copying to rcNew.

**Comment by flackr** [comment]
> The clang complaint https://github.com/CorsixTH/CorsixTH/runs/6442929540?check_suite_focus=true#step:11:84 looks legit; you removed the get_clip_rect that was populating rcOld before copying to rcNew.

Yep, that's a simple fix. Since the clip rects are always intersected we can just prepopulate y = 0, h = height.

**Comment by flackr** [comment]
Verified the UIMessage seems to still be working too :-).

**Pull request merged**
