### PR TITLE
[RFC/RDY] Dedication to the IRC

### PR DESCRIPTION
**Pull request by lewri**
Just some fun additions to staff description.

### CODE REVIEW

**Comment by lewri** [comment]
Working on making this code friendly :(

**Comment by lewri** [comment]
Not easily fixable right now to be properly keyed. But in all ways we init the language makes a mismatched key number not matter. Have discussed with @Alberth289346 and it will need to be made better at some point but there are several hurdles to overcome before that.

**Comment by TheCycoONE** [comment]
Well this did encourage me to take a deeper look at how __random is implemented in `th_lua_strings.cpp`. It's an 'interesting' implementation. I may add a unit test and re-implement it with fewer C<->Lua transitions.

**Comment by lewri** [comment]
Just to add a note so I don't keep forgetting -- I believe Corsix's original workaround for dedications was putting it inside the original strings lua file. But I don't think it'd work in this case.

**Comment by lewri** [comment]
Closing until there's a better implementation for this

**Pull request closed without merging**
