### PR TITLE
fix copyright header of AnimView/rnc.cpp

### PR DESCRIPTION
**Pull request by a-detiste**
Hi,

This made the Debian FTP Masters angry :sweat: 
Hopefully the .zip archive does include a licens :smile:

### CODE REVIEW

**Comment by a-detiste** [comment]
P.S.: that makes sense, the LICENSE.TXT is dated 2014; so years after inclusion of this code into Corsix-TH.

**Comment by corsix** [comment]
Nice sleuthing, and nice to see licensing/copyright status resolved. Merging.

**Comment by corsix** [comment]
Although it seems that possibly past-me possibly considered this in 2009 (see https://github.com/CorsixTH/CorsixTH/commit/7af98d5e1df814d3cafa276ff55ecd1e12ab6c01). Good past-me. It would also seem that past-me duplicated the RNC code to two places, and only updated the licensing notes in one of those places. Bad past-me.

**Comment by TheCycoONE** [comment]
I fixed an invalid read in rnc.cpp a few years ago, I bet it's also still in the AnimView version. Consolidation will go in the TODO list.

**Pull request merged**
