### PR TITLE
[NRDY] Lower the music *held*

### PR DESCRIPTION
**Pull request by lewri**
Resolves part of #1935

**Describe what the proposed change does**
- Set default music to 0.2 instead of 0.5 for first launch.

### CODE REVIEW

**Comment by lewri** [comment]
If 1978 is actually what caused the blaring in the first place this PR might not be needed.

**Comment by TheCycoONE** [comment]
Let's fix 1978 and see where it takes us.

**Comment by TheCycoONE** [comment]
This isn't actually [RDY] is it? I keep coming back to it, but iirc it doesn't solve the problem?

**Comment by lewri** [comment]
Not really anything at the moment -- but there's nothing to do with it either.
Should change it to the rare [NRDY]

**Comment by lewri** [comment]
On some additional testing, the adjustment is still needed. Just no benefit using it yet.

**Comment by lewri** [comment]
Closing for now awaiting 1978

**Pull request closed without merging**
