### PR TITLE
Remove 'Flag' macro for setting tile node flag values.

### PR DESCRIPTION
**Pull request by Alberth289346**

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Actually, this looks like a perfect candidate for std::map. Something like:
```
std::map<const char *, THMapNodeFlags> lua_node_flag_map = {
    {"passable", THMN_Passable},
    {"hospital", THMN_Hospital},
...
auto iter = lua_node_flag_map.find(field);
if(iter != lua_node_flag_map.end())
{
  if (lua_toboolean(L, 6) == 0)
    pNode->iFlags &= ~((*iter).second);
...
```

* Above was written by hand in this comment section, untested, I can't vouch for it but I think it should work.

**Comment by TheCycoONE** [comment]
Actually you'll need to either specify an alternate compare function or use std::string for the key.

**Comment by Alberth289346** [comment]
Suggestion implemented

**Comment by Alberth289346** [comment]
Good suggestion.

Moved lua_node_flag_map up, and re-used it for getcellflags.

**Comment by Alberth289346** [comment]
Updated to "val"

**Comment by TheCycoONE** [comment]
TravisCI failure caused by https://github.com/Olivine-Labs/busted/issues/459, we can ignore it.

**Comment by TheCycoONE** [comment]
Lets merge these commits, the second rewrites a lot of the first anyway.

**Comment by TheCycoONE** [comment]
Merged with squash.

**Pull request closed without merging**
