### PR TITLE
Dockerfile added for building corsixth

### PR DESCRIPTION
**Pull request by lastcosmonaut**
Tell me if it's useful to you. Thanks!

### CODE REVIEW

**Comment by TheCycoONE** [comment]
I'm not personally experienced enough with Docker to review this, but I don't see the harm in including it as long as it's maintained, and the documentation on how to use it is added either to this file (comments) or the wiki.

@emorrp1 are you able to look at this?

Should we specify a particular version of Ubuntu? `latest` makes me nervous.

**Comment by emorrp1** [comment]
Yes, I'll look into this at the weekend. I suspect "latest" is probably fine.

**Comment by romualdr** [comment]
well, FYI this still works in 2020 - I mostly used the `apt-get` commands to get the dependencies in my own Dockerfile to create a build environment to play with the source code, and it still works like a charm with ubuntu `latest`

**Comment by TheCycoONE** [comment]
If it's useful to you, I'll merge it.

**Pull request merged**
